Select 
Part.PartNum AS 'PartNum',
Part.PartDescription AS 'Description',
Part.TypeCode AS 'M/P',
Part.OnHold,
Part.UOMClassID AS 'UoMClass',
Part.IUM AS 'InvntryUoM',
Part.SalesUM AS 'SalesUoM',
Part.PUM AS 'PurchaseUoM',
Part.ProdCode AS 'ProdGroup',
Part.ClassID AS 'Class',
Part.AnalysisCode AS 'USMapping',
Part.MtlAnalysisCode AS 'PhocusPG',
Part.NonStock,
Part.RunOut,
Part.UsePartRev,
Part.PartSpecificPackingUOM,
Part.TrackDimension,
Part.ConsolidatedPurchasing,
Part.SubLevelCode,
Part.Constrained,
Part.MDPV AS 'MaximumDailyProdValue',
PartPlant.PhantomBOM,
PartPlant.BackFlush,
PartPlant.LimitProdYldRecalc,
PartPlant.MultiLevelCTP,
PartPlant.GenerateSugg AS 'GeneratePOSuggestions',
PartPlant.BuyToOrder,
PartPlant.DropShip,
PartPlant.MinimumQty AS 'MinOnHand',
PartPlant.MaximumQty AS 'MaxOnHand',
PartPlant.SafetyQty AS 'SafetyStock',
PartPlant.ReOrderLevel AS 'ReOrderToMax',
PartPlant.MMSHistory AS 'CalculateMMSHisWidndow',
PartPlant.MMSSafetyFactor AS 'CalculateMMSSafetyFactor',
PartPlant.MMSMaxFactor AS 'CalculateMMSMaxFactor',
PartPlant.BuyerID AS 'BuyerID',
PartPlant.VendorNum AS 'PrefVendor',
PartPlant.MinOrderQty AS 'BuyingMOQ',
PartPlant.LeadTime AS 'StdLeadTime',
PartPlant.UrgentVendorNum AS 'UrgentVendor',
PartPlant.UrgentMinOrdQty AS 'UrgentBuyingMOQ',
PartPlant.UrgentLeadTime,
PartPlant.UrgentMultQty AS 'UrgentMultQty',
PartPlant.PlanTimeFence AS 'PlanningTimeFence',
PartPlant.ReschedInDelta AS 'RescheduleInDelta',
PartPlant.ReschedOutDelta AS 'RescheduleOutDelta',
PartPlant.AltMethod AS 'PrimaryAlternateMethod',
PartPlant.MfgLotMultiple,
PartPlant.MinMfgLotSize,
PartPlant.MaxMfgLotSize,
PartPlant.DaysOfSupply,
PartPlant.StartMinLotQty,
PartPlant.MinLotLeadTime,
PartPlant.MinStartQty,
PartPlant.ShortHorizonDays,
PartPlant.ShortHorizonMinMfgLotSize,
PartPlant.ShortHorizonMaxMfgLotSize,
PartPlant.ShortHorizonDaysSupp AS 'ShortHorizonDaysOfSupply',
PartPlant.MfgLeadTimeMnl AS 'MfgLeadTimeManualSet',
PartPlant.PrepTime AS 'PrepartionTime',
PartPlant.KitTime,
PartPlant.ReceiveTime,
PartPlant.TotMfgLeadTimeSys AS 'SysCalcMfgLeadTime',
PartPlant.LvlMfgLeadTimeSys AS 'SysCalcThisLevelLeadTime',
PartPlant.TopLvlMfgLeadTimeSys AS 'SysCalcTopLevelLeadTime',
PartPlant.MfgLeadTimeCalcDate AS 'LastCalcDateMfgLeadTime',
PartPlant.AutoConsumeStock,
PartPlant.TransferLeadTime
FROM Part INNER JOIN PartPlant
ON Part.PartNum = PartPlant.PartNum 
WHERE PartPlant.Plant = 'GLENDN'
AND Part.InActive = 0
AND (PartPlant.ReschedInDelta <> 0 OR PartPlant.ReschedOutDelta <> 0)

SELECT * FROM erp.SugPoDtl WHERE PartNum = 'A-FHN147588'

SELECT * FROM PLP_PowerBI.dbo.StockOuts